### ISSUE TITLE
VTS L1 Enhancement - Test Profile Changes - Power Manager

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-power_manager#11]
This task is to modify the L1 concerning the latest Test profile changes if any. If there are no changes concerning the test profile, this Jira can be closed with proper information.

Interface file:
https://github.com/rdkcentral/rdk-halif-power_manager/blob/main/include/plat_power.h

L1 File:
https://github.com/rdkcentral/rdk-halif-test-power_manager/blob/develop/src/test_l1_plat_power.c

**Comment by Sumip98** [comment]
There are no changes in the power manager concerning the test profile.

**Comment by srinivasgtl** [comment]
To recheck again with the profiles sink_powerManager.yaml and source_powerManager.yaml

**Comment by srinivasgtl** [comment]
This is now merged.
