### ISSUE TITLE
L3 - Power Manager - Correct error in L3 tests

### ISSUE THREAD

**Issue by hgfell683** [rdkcentral/rdk-halif-test-power_manager#28]
There is an error within the setWakeUpSource test, where for a booleon where we are supposed to check that the enabled value is within the proper bounds, but we are checking it against sourceType, which is causing the test to fail out when a wake up source greater then 1 is selected. This is to fix this issue, and check the correct variables bounds such that it does not fail.

**Comment by akhilbhas** [comment]
Merged to develop
